# Generated by Django 5.1.3 on 2024-11-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cli_cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=50)),
                ('cli_apellido', models.CharField(max_length=50)),
                ('cli_correo', models.EmailField(max_length=100, unique=True)),
                ('cli_celular', models.CharField(max_length=15)),
                ('cli_direccion', models.TextField()),
                ('cli_contrasenia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(max_length=100)),
                ('prov_numero', models.CharField(max_length=15)),
                ('prov_correo', models.EmailField(max_length=100, unique=True)),
                ('prov_contrasenia', models.CharField(max_length=100)),
                ('prov_direccion', models.TextField()),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='OrdenCli',
            fields=[
                ('orden_id', models.AutoField(primary_key=True, serialize=False)),
                ('orden_fecha', models.DateField()),
                ('orden_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_cli_cedula', models.ForeignKey(db_column='fk_cli_cedula', on_delete=django.db.models.deletion.CASCADE, to='postgres.clientes')),
            ],
            options={
                'db_table': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_descripcion', models.CharField(max_length=200)),
                ('prod_stock', models.IntegerField()),
                ('prod_imagen', models.TextField()),
                ('prod_precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_categoria_id', models.ForeignKey(db_column='fk_categoria_id', on_delete=django.db.models.deletion.CASCADE, to='postgres.categoria')),
                ('fk_prov_id', models.ForeignKey(db_column='fk_prov_id', on_delete=django.db.models.deletion.CASCADE, to='postgres.proveedor')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_id', models.IntegerField()),
                ('detalle_cantidad', models.IntegerField()),
                ('detalle_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_orden_id', models.ForeignKey(db_column='fk_orden_id', on_delete=django.db.models.deletion.CASCADE, to='postgres.ordencli')),
                ('fk_prod_id', models.ForeignKey(db_column='fk_prod_id', on_delete=django.db.models.deletion.CASCADE, to='postgres.producto')),
            ],
            options={
                'db_table': 'detalle_ordenes',
                'constraints': [models.UniqueConstraint(fields=('detalle_id', 'fk_orden_id'), name='unique_detalle_orden')],
                'unique_together': {('detalle_id', 'fk_orden_id')},
            },
        ),
    ]
